import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://jgaknhtgpsghebhruxvt.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnYWtuaHRncHNnaGViaHJ1eHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTQyNzAsImV4cCI6MjA3MTc3MDI3MH0.8EEG20g9fvkP1OnC7L618q31T1JXx7CGYpZ8aD8lfQ8'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Service role client for admin operations (use carefully)
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnYWtuaHRncHNnaGViaHJ1eHZ0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjE5NDI3MCwiZXhwIjoyMDcxNzcwMjcwfQ.MjAj8XUpfIYBlZu81RmKEUcRsdq-Mt07sRcI9XN6xUQ'
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey)
